import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";

/**
 * The Deno copy at supabase/functions/_shared/medical-lexicon.ts must stay in step
 * with the pure region of src/lib/medicalLexicon.ts.
 *
 * Edge functions can't import from src/, and vitest can't see supabase/functions/ —
 * the same constraint that produced the platform-billing duplicate (see
 * platformBilling.parity.test.ts). Here the stakes are patient safety rather than
 * money: the four-condition gate in `shouldAutoApply` is what stops a transcript word
 * being silently rewritten into a drug name, and it is ONLY exercised by unit tests
 * against the src/ copy. If the Deno copy drifts, the code that actually runs in
 * production is the untested one.
 *
 * Because the Deno file is generated by slicing the marked region verbatim, parity is
 * asserted byte-for-byte rather than by comparing normalised function bodies.
 */

const ROOT = path.resolve(__dirname, "../..");
const SRC = path.join(ROOT, "src/lib/medicalLexicon.ts");
const DENO = path.join(ROOT, "supabase/functions/_shared/medical-lexicon.ts");

const START = "// ── region:pure";
const END = "// ── endregion:pure";

function pureRegion(source: string): string {
  const a = source.indexOf(START);
  const b = source.indexOf(END);
  expect(a, "region:pure marker missing").toBeGreaterThan(-1);
  expect(b, "endregion:pure marker missing").toBeGreaterThan(a);
  return source.slice(a, b).trimEnd();
}

describe("medicalLexicon Deno parity", () => {
  const srcText = fs.readFileSync(SRC, "utf8");
  const denoText = fs.readFileSync(DENO, "utf8");
  const region = pureRegion(srcText);

  it("carries the pure region byte-for-byte into the Deno copy", () => {
    expect(
      denoText.includes(region),
      "supabase/functions/_shared/medical-lexicon.ts has drifted from src/lib/medicalLexicon.ts — " +
        "re-copy the region between the region:pure markers.",
    ).toBe(true);
  });

  it("carries the safety gate specifically", () => {
    // Called out on its own so a drift here names the thing that actually broke.
    for (const marker of [
      "export function shouldAutoApply",
      "if (!phoneticExact) return false;",
      "COMMON_ENGLISH_WORDS.has(sourceWords[0].toLowerCase())",
      "if (candidateScore - runnerUpScore < ambiguityMargin) return false;",
    ]) {
      expect(denoText, `safety gate drifted: ${marker}`).toContain(marker);
    }
  });

  it("keeps every exported symbol of the pure region", () => {
    const exported = [...region.matchAll(/export (?:function|const|interface|type) (\w+)/g)]
      .map(m => m[1]);
    expect(exported.length).toBeGreaterThan(5);
    for (const name of exported) {
      expect(denoText, `${name} missing from the Deno copy`).toMatch(
        new RegExp(`export (?:function|const|interface|type) ${name}\\b`),
      );
    }
  });

  it("adds the Deno-only loading layer that has no src/ counterpart", () => {
    expect(denoText).toContain("export async function loadHospitalLexicon");
    expect(denoText).toContain("export function topHotwords");
    // ...and those must NOT leak back into the browser bundle.
    expect(srcText).not.toContain("loadHospitalLexicon");
  });
});
