import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: 'patients',
      columns: [
        { name: 'remote_id', type: 'string' },
        { name: 'hospital_id', type: 'string', isIndexed: true },
        { name: 'uhid', type: 'string', isIndexed: true },
        { name: 'full_name', type: 'string' },
        { name: 'date_of_birth', type: 'string', isOptional: true },
        { name: 'gender', type: 'string', isOptional: true },
        { name: 'phone', type: 'string', isOptional: true },
        { name: 'blood_group', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'appointments',
      columns: [
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'hospital_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'patient_name', type: 'string' },
        { name: 'uhid', type: 'string' },
        { name: 'doctor_id', type: 'string', isIndexed: true },
        { name: 'appointment_date', type: 'string' },
        { name: 'slot_time', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'reason', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'vitals',
      columns: [
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'hospital_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'recorded_by', type: 'string' },
        { name: 'recorded_at', type: 'number' },
        { name: 'temperature', type: 'number', isOptional: true },
        { name: 'pulse', type: 'number', isOptional: true },
        { name: 'bp_systolic', type: 'number', isOptional: true },
        { name: 'bp_diastolic', type: 'number', isOptional: true },
        { name: 'spo2', type: 'number', isOptional: true },
        { name: 'respiratory_rate', type: 'number', isOptional: true },
        { name: 'news2_score', type: 'number', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'prescriptions',
      columns: [
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'hospital_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'prescribed_by', type: 'string' },
        { name: 'prescribed_at', type: 'number' },
        { name: 'drug_name', type: 'string' },
        { name: 'dose', type: 'string' },
        { name: 'frequency', type: 'string' },
        { name: 'route', type: 'string' },
        { name: 'duration_days', type: 'number', isOptional: true },
        { name: 'instructions', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'ward_rounds',
      columns: [
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'hospital_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'doctor_id', type: 'string', isIndexed: true },
        { name: 'rounded_at', type: 'number' },
        { name: 'subjective', type: 'string', isOptional: true },
        { name: 'objective', type: 'string', isOptional: true },
        { name: 'assessment', type: 'string', isOptional: true },
        { name: 'plan', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'mar_entries',
      columns: [
        { name: 'remote_id', type: 'string', isOptional: true },
        { name: 'hospital_id', type: 'string', isIndexed: true },
        { name: 'patient_id', type: 'string', isIndexed: true },
        { name: 'prescription_id', type: 'string', isIndexed: true },
        { name: 'drug_name', type: 'string' },
        { name: 'dose', type: 'string' },
        { name: 'scheduled_time', type: 'number' },
        { name: 'administered_at', type: 'number', isOptional: true },
        { name: 'administered_by', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'reason_held', type: 'string', isOptional: true },
        { name: 'is_synced', type: 'boolean' },
        { name: 'synced_at', type: 'number', isOptional: true },
      ],
    }),
  ],
});
