// AI Clarifying Questions — OPD AI Guidance tab.
//
// Proposes the fewest, highest-yield questions that would narrow the differential for THIS
// patient, given everything documented so far. The doctor answers them; the answers land in
// the HPI and the differential is re-run against the richer history.
//
// SaMD Class B (Decision Support) — see 20261012000031_add_clarifying_questions_prompt.sql.
//
// PHI HANDLING (Ananya): the request body carries chief complaint, examination notes, chronic
// conditions and — when the doctor leaves it enabled — the tail of the voice-scribe transcript.
// NOTHING in this function may console.log the request body or any field of it. The only
// logging here is error NAMES and metering counts. The transcript is read and discarded; it is
// never written to any table.
//
// Modelled on ai-differential-diagnosis/index.ts, with three deliberate differences:
//   1. Reads the system prompt from prompt_registry (Dr. Nalini: prompts must be versioned),
//      with a byte-identical inline fallback so a missing seed degrades to "works, unversioned"
//      rather than "silently sends no system prompt at all" — which is what would happen on the
//      ai-proxy path, since ai-proxy only consults the registry when the client sends none.
//   2. Passes hospital_id + feature key to the ENV fallback too. ai-differential-diagnosis
//      calls resolveAiConfigFromEnv(1000) bare, so its env-fallback branch spends real money
//      with no meter attached and the cost is invisible.
//   3. Catches AIDisabledError and answers 403, so the card can render "disabled by your
//      administrator" instead of a generic failure.

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  resolveAiConfig,
  resolveAiConfigFromEnv,
  callAiChat,
  AIDisabledError,
} from "../_shared/ai-config.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const FEATURE_KEY = "clarifying_questions";
const MAX_TOKENS = 700;

/**
 * Bumped ONLY together with a new prompt_registry row. This is the version reported when the
 * registry lookup finds nothing, so the fallback text below must stay byte-identical to the
 * seeded prompt — otherwise a stored question set would claim a version it wasn't generated by,
 * which defeats the whole point of stamping prompt_version onto the record.
 */
const PROMPT_VERSION = 1;

const FALLBACK_SYSTEM_PROMPT =
  `You are a senior physician assisting a doctor during an Indian hospital OPD consultation. ` +
  `You receive everything documented about the patient so far. Your job is to propose the ` +
  `FEWEST, HIGHEST-YIELD questions that would most narrow the differential diagnosis. ` +
  `Return AT MOST 5 questions. Return FEWER — or an empty array — when the documented history ` +
  `already discriminates between the likely diagnoses. More questions is NOT better: a busy ` +
  `OPD doctor will ignore a long list, and an ignored list is worse than no list. ` +
  `Each question must be answerable Yes or No, phrased NEUTRALLY (never leading, never ` +
  `presupposing the answer), in plain Indian English simple enough to be translated to the ` +
  `patient at the bedside. ` +
  `Each question MUST name which differential diagnosis it rules IN and which it rules OUT — ` +
  `a question that discriminates nothing does not belong in the list. ` +
  `NEVER ask something already documented in the input. List anything you found already ` +
  `answered under "already_known" instead, so the doctor can see you read the chart. ` +
  `Prioritise Indian epidemiology over Western textbook priors: dengue, enteric fever, ` +
  `tuberculosis, malaria and scrub typhus in undifferentiated fever; rheumatic heart disease ` +
  `in a young patient with a murmur; South Asians develop coronary artery disease at a lower ` +
  `BMI and a younger age than Western cohorts, so do not dismiss cardiac causes on age or ` +
  `build alone. Consider TB exposure, well-water and street-food exposure, and recent travel ` +
  `within India. ` +
  `Set red_flag true for any question screening for a condition that would need emergency ` +
  `action today. ` +
  `Use Indian English spelling (anaesthesia, gynaecology, oedema, diarrhoea). ` +
  `Return ONLY valid JSON — no markdown, no code fences, no prose before or after the object: ` +
  `{"questions":[{"id":"q1","rank":1,"question":"<string>","why":"<one sentence: what this ` +
  `discriminates and why it matters>","rules_in":["<diagnosis>"],"rules_out":["<diagnosis>"],` +
  `"yield":0.0-1.0,"red_flag":<boolean>,"category":"history|red_flag|exam|risk_factor|` +
  `medication|travel_exposure"}],"already_known":["<string>"],"notes":"<string or null>"}. ` +
  `yield is your estimate of how much answering this would narrow the differential (1.0 = ` +
  `decisive). rank orders the questions, most useful first. ` +
  `These are prompts for the treating doctor to CONSIDER asking. They are never a diagnosis, ` +
  `never a substitute for the doctor's own history-taking, and the doctor decides what to ask.`;

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    // Auth verification — this endpoint derives AI output from a real patient's chart
    // (prior visits, diagnoses); it must never be reachable without a valid session, and
    // hospital_id must never be trusted from the caller (see the service-role note below).
    const authHeader = req.headers.get("Authorization");
    if (!authHeader?.startsWith("Bearer ")) {
      return json({ error: "Unauthorized" }, 401);
    }
    const anonClient = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_ANON_KEY")!);
    const { data: { user }, error: authError } = await anonClient.auth.getUser(authHeader.replace("Bearer ", ""));
    if (authError || !user) {
      return json({ error: "Unauthorized" }, 401);
    }

    const {
      chief_complaint,
      history,
      onset,
      vitals,
      examination,
      systemic_examination,
      age,
      gender,
      allergies,
      chronic_conditions,
      current_diagnosis,
      voice_transcript,
      prior_history_digest,
      patient_id,
      encounter_id,
    } = await req.json();

    if (!chief_complaint) {
      return json({ error: "chief_complaint is required" }, 400);
    }

    const sb = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
    );

    // Resolve hospital from the authenticated user — never trust hospital_id from the request body.
    const { data: userData } = await sb
      .from("users")
      .select("hospital_id")
      .eq("auth_user_id", user.id)
      .maybeSingle();
    if (!userData) {
      return json({ error: "Forbidden" }, 403);
    }
    const hospital_id = userData.hospital_id;

    // ── AI config. resolveAiConfig also enforces the hospital's AI entitlement and THROWS
    // AIDisabledError when the feature is withheld — caught below and turned into a 403 so
    // the card renders a proper disabled state rather than a generic failure.
    const config =
      (await resolveAiConfig(hospital_id || "", FEATURE_KEY, MAX_TOKENS)) ??
      resolveAiConfigFromEnv(MAX_TOKENS, hospital_id || undefined, FEATURE_KEY);

    if (!config) {
      return json({ error: "No AI provider configured. Go to Settings → API Hub." }, 503);
    }

    // Attribute the spend to this patient/encounter. resolveAiConfig cannot know these, and
    // without them the row in ai_usage_logs is unattributable PHI-adjacent spend.
    if (config.meter) {
      config.meter = {
        ...config.meter,
        patientId: patient_id || undefined,
        encounterId: encounter_id || undefined,
      };
    }

    // ── Versioned system prompt.
    const { data: reg } = await sb
      .from("prompt_registry")
      .select("system_prompt, version")
      .eq("feature_key", FEATURE_KEY)
      .eq("is_active", true)
      .maybeSingle();

    const systemPrompt = reg?.system_prompt || FALLBACK_SYSTEM_PROMPT;
    const promptVersion = Number(reg?.version) || PROMPT_VERSION;

    // ── Prior visits for this patient. Scoped by hospital_id as well as patient_id: this is a
    // SERVICE-ROLE client, so RLS does not protect us here and patient_id alone would be the
    // one place in this feature a cross-tenant read could occur.
    let priorVisits = "";
    if (patient_id && hospital_id) {
      const { data: prior } = await sb
        .from("opd_encounters")
        .select("visit_date, diagnosis, chief_complaint")
        .eq("patient_id", patient_id)
        .eq("hospital_id", hospital_id)
        .neq("id", encounter_id || "00000000-0000-0000-0000-000000000000")
        .order("visit_date", { ascending: false })
        .limit(3);

      const rows = Array.isArray(prior) ? prior : [];
      if (rows.length > 0) {
        priorVisits = rows
          .map((v: Record<string, unknown>) =>
            `  • ${v.visit_date ?? "date unknown"}: ${v.diagnosis || v.chief_complaint || "no diagnosis recorded"}`)
          .join("\n");
      }
    }

    // The transcript is already truncated client-side; re-cap here so a hand-rolled request
    // cannot blow the token budget. Data minimisation, and a hard ceiling on cost per call.
    const transcript = typeof voice_transcript === "string" ? voice_transcript.slice(-4000) : "";

    // The patient's history from the OUTSIDE records they brought in, already summarised and
    // capped client-side by formatDigestForPrompt. Re-capped here for the same reason as the
    // transcript: a hand-rolled request must not be able to blow the token budget.
    //
    // Its own provenance prefix ("AI-extracted … NOT hospital-verified") is part of the string
    // and must reach the model intact — a transcribed handwritten prescription is a lead, and
    // a model told nothing will treat it as this hospital's own record.
    const priorHistory = typeof prior_history_digest === "string"
      ? prior_history_digest.slice(0, 2000)
      : "";

    const userPrompt = `Documented so far in this OPD consultation:
- Chief Complaint: ${chief_complaint}
- History of Present Illness: ${history || "not documented"}
- Onset: ${onset || "not documented"}
- Age: ${age || "unknown"}, Gender: ${gender || "unknown"}
- Vitals: ${JSON.stringify(vitals || {})}
- General Examination: ${examination || "not documented"}
- Systemic Examination: ${systemic_examination || "not documented"}
- Known Allergies: ${allergies || "none recorded"}
- Chronic Conditions: ${chronic_conditions || "none recorded"}
- Working Diagnosis (if any): ${current_diagnosis || "not yet reached"}
${priorVisits ? `- Previous visits at this hospital:\n${priorVisits}` : "- Previous visits: none on record"}
${priorHistory ? `\n${priorHistory}\nAnything the above already answers must go under "already_known" — do NOT ask the patient about it again.` : ""}
${transcript ? `\nDoctor-patient conversation transcript (may be partial or contain transcription errors — treat as a hint, not as documented fact):\n"""\n${transcript}\n"""` : ""}

Propose at most 5 clarifying questions that would most narrow the differential. Return the JSON object described in your instructions and nothing else.`;

    const content = await callAiChat(
      config,
      [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      MAX_TOKENS,
      0.2,
    );

    const parsed = JSON.parse(
      content.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim(),
    );

    return json({ ...parsed, prompt_version: promptVersion });
  } catch (err) {
    // AI withheld for this hospital → 403, so the card shows a disabled state.
    if (err instanceof AIDisabledError) {
      return json({ error: err.message, disabled: true }, 403);
    }
    // NEVER echo the request body or the model output here — both carry PHI. The error name
    // and message from a JSON.parse failure are safe; the offending text is not.
    const name = err instanceof Error ? err.name : "UnknownError";
    console.error(`ai-clarifying-questions failed: ${name}`);
    return json(
      { error: name === "SyntaxError" ? "AI returned an unreadable response." : "AI request failed." },
      500,
    );
  }
});
