// AI History Ingest — reads a patient's bag of outside medical records, page by page.
//
// A rural OPD patient arrives with hundreds of pages of old prescriptions, discharge
// summaries and lab reports. This worker transcribes every page and extracts dated clinical
// events from it. ai-history-digest then merges the result into one timeline.
//
// ── WHY THIS IS A SELF-RE-INVOKING WORKER AND NOT A PLAIN FUNCTION ──────────────────────
// 300 pages is ~20 AI calls at 10-30s each. No edge function invocation survives that. So
// the unit of work is ONE CHUNK (15 pages), the unit of scheduling is a ~90s wall budget,
// and when the budget runs out the worker re-invokes itself and returns. State lives
// entirely in patient_history_source_chunks, so a worker that dies mid-run loses at most
// one chunk — which the next invocation re-queues.
//
// ── THE COVERAGE CONTRACT ───────────────────────────────────────────────────────────────
// The feature's whole promise is "no page was missed". That is only true if a page that
// CANNOT be read still leaves a visible row. So: every page of every source gets exactly one
// chunk row, an unreadable chunk ends as status='failed' (never deleted, never skipped), and
// finalize_history_job() reports the job 'partial' rather than 'complete'. Any change here
// that makes a page disappear from the ledger breaks the only claim that matters.
//
// ── PHI HANDLING (Ananya) ───────────────────────────────────────────────────────────────
// Everything this function touches is third-party clinical PHI. NOTHING may console.log the
// request body, a storage path, a model response, or verbatim_text. The only logging is
// error NAMES and counts — same rule as ai-clarifying-questions.
//
// ── THE SERVICE-ROLE TENANT TRAP (Ananya) ───────────────────────────────────────────────
// This runs under the service role, so RLS does not protect it. EVERY read filters
// hospital_id in addition to job_id / source_id / patient_id. The hospital_id is taken from
// the JOB ROW, never from the request body — a caller who could name someone else's job_id
// must not also get to name the hospital it is checked against.
//
// Modes:
//   { job_id }                    process chunks (the normal path)
//   { job_id, retry_failed: true } re-queue failed chunks, then process
//   { sweep: true }               purge expired/stalled staging only (hourly pg_cron)

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  resolveAiConfig,
  resolveAiConfigFromEnv,
  callAiDocument,
  callAiChatWithUsage,
  supportsPdfDocuments,
  AIDisabledError,
  type AiConfig,
} from "../_shared/ai-config.ts";
import { checkAIAllowed } from "../_shared/ai-entitlement.ts";
import { slicePdf, pageRanges, bytesToBase64, DEFAULT_PAGES_PER_CHUNK } from "../_shared/pdf-split.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const FEATURE_KEY = "history_document_extract";
const BUCKET = "patient-documents";
const MAX_TOKENS = 4000;
const PAGES_PER_CHUNK = DEFAULT_PAGES_PER_CHUNK;

/** Leaves headroom under the platform wall-clock limit for the final writes + re-invoke. */
const WALL_BUDGET_MS = 90_000;

/** A chunk gets three goes before the ledger records it as unreadable. */
const MAX_ATTEMPTS = 3;

/** A chunk left 'running' this long belonged to an invocation that died. */
const STALE_CHUNK_MINUTES = 5;

/**
 * Bumped ONLY together with a new prompt_registry row. Reported when the registry lookup
 * finds nothing, so this text must stay byte-identical to the seeded prompt in
 * 20261013000011 — otherwise a stored extraction claims a version it was not generated by,
 * which defeats the point of stamping prompt_version at all.
 */
const PROMPT_VERSION = 1;

const FALLBACK_SYSTEM_PROMPT =
  `You are a medical records transcriptionist for an Indian hospital. You are given one ` +
  `document, or a range of pages from one document, that a patient has brought from OUTSIDE ` +
  `this hospital — an old prescription, a discharge summary, a lab report, a scan report. ` +
  `Your output becomes the permanent record of what this paper said, because the scan itself ` +
  `is discarded after you read it. ` +
  `WORK IN TWO PASSES, IN THIS ORDER. ` +
  `PASS 1 — TRANSCRIBE. Reproduce everything legible on these pages as plain text: headings, ` +
  `dates, doctor and hospital names, every drug with its dose and frequency, every lab value ` +
  `with its unit and reference range, every handwritten annotation. Preserve the order it ` +
  `appears in. Do NOT summarise, do NOT skip anything you judge unimportant, do NOT correct ` +
  `what you think is a mistake. ` +
  `PASS 2 — STRUCTURE. Only now turn that transcription into dated clinical events. ` +
  `NEVER GUESS. If a value, dose, date or word is illegible, write it as "[illegible]" and keep ` +
  `the surrounding context so a doctor can see what was there and check the paper themselves. ` +
  `An illegible dose recorded as "[illegible]" is safe; an invented dose can kill a patient. ` +
  `Never omit an illegible item silently — list it under "unreadable" so it is visible. ` +
  `DATES. Indian documents write dates as DD/MM/YYYY or DD-MM-YY; read them that way, never as ` +
  `the American MM/DD. Emit every date as YYYY-MM-DD. When a date is partial ("March 2019") use ` +
  `the first of the month and set date_confidence "approximate". When there is no date at all, ` +
  `use null and "unknown" — never invent one and never assume today. ` +
  `REGIONAL SCRIPT. Annotations in Telugu, Hindi, Tamil, Kannada, Malayalam, Bengali, Marathi or ` +
  `Gujarati must be transcribed in the original script AND translated to English. Keep both. ` +
  `INDIAN CLINICAL CONTEXT. Expect Indian brand names (Crocin, Augmentin, Glycomet, Telma, ` +
  `Pan-D) — record the brand exactly as written and add the generic in the detail when you are ` +
  `certain of it. Expect Indian lab reference ranges and units. Expect abbreviations used in ` +
  `Indian practice: OD, BD, TDS, QID, HS, SOS, stat, x5d, T., Tab., Cap., Inj., Syp. ` +
  `Use Indian English spelling (anaesthesia, gynaecology, oedema, diarrhoea, haemoglobin). ` +
  `SIGNIFICANCE and red_flag. Mark red_flag true ONLY for something a doctor would need to act ` +
  `on today — a documented drug allergy or anaphylaxis, a malignancy, a prior MI or stroke, ` +
  `active TB, a critical unrepeated lab value, a prior serious adverse drug reaction. A long ` +
  `red-flag list trains doctors to ignore the whole record, which is worse than none. ` +
  `Return ONLY valid JSON — no markdown, no code fences, no prose before or after the object: ` +
  `{"verbatim_text":"<the full pass-1 transcription>","document_type":"<prescription|` +
  `discharge_summary|lab_report|imaging_report|operative_note|vaccination_record|` +
  `insurance_document|referral_letter|other>","document_date":"<YYYY-MM-DD or null>",` +
  `"facility":"<issuing hospital/clinic/lab or null>","events":[{"date":"<YYYY-MM-DD or null>",` +
  `"date_confidence":"exact|approximate|unknown","type":"visit|diagnosis|medication|` +
  `investigation|procedure|admission|allergy|vaccination|note","facility":"<string or null>",` +
  `"title":"<short label>","detail":"<one or two sentences>","values":[{"name":"<string>",` +
  `"value":"<string>","unit":"<string or null>","ref":"<reference range or null>"}],` +
  `"medications":[{"name":"<as written>","dose":"<string or null>","frequency":"<string or ` +
  `null>","duration":"<string or null>"}],"significance":"high|medium|low","red_flag":<boolean>,` +
  `"verbatim":"<the exact transcribed line this event came from>"}],` +
  `"unreadable":["<page or region and what could not be read>"]}. ` +
  `You are transcribing a record, not diagnosing a patient. Never add a diagnosis, a dose or a ` +
  `finding that is not physically on these pages.`;

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });

const admin = () =>
  createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

/** Strip markdown fences and any prose either side of the object. */
function parseModelJson(raw: string): Record<string, unknown> {
  const cleaned = raw.replace(/```json\n?/gi, "").replace(/```\n?/g, "").trim();
  const start = cleaned.indexOf("{");
  const end = cleaned.lastIndexOf("}");
  return JSON.parse(start >= 0 && end > start ? cleaned.slice(start, end + 1) : cleaned);
}

/** ISO date or null. The model is not trusted to honour its own schema. */
function safeDate(v: unknown): string | null {
  if (typeof v !== "string") return null;
  const m = v.trim().match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!m) return null;
  const d = new Date(v);
  if (Number.isNaN(d.getTime())) return null;
  // A record dated in the future is a misread year (2019 → 2029 is one stroke on a scan),
  // not a real event. Drop the date rather than putting the patient's past in their future.
  if (d.getTime() > Date.now() + 86_400_000) return null;
  return v.trim();
}

const str = (v: unknown, max = 2000): string | null => {
  if (typeof v !== "string") return null;
  const t = v.trim();
  return t ? t.slice(0, max) : null;
};

const EVENT_TYPES = new Set([
  "visit", "diagnosis", "medication", "investigation", "procedure",
  "admission", "allergy", "vaccination", "note",
]);

/**
 * Defensive clamp on the model's events.
 *
 * Deliberately does NOT drop an event for a missing date, a bad type or an unknown
 * significance — it normalises them. An undated event is still a real finding on the paper,
 * and silently discarding it would be exactly the "missed something" failure this feature
 * exists to prevent. The only thing that disqualifies an event is having no title at all.
 */
function clampEvents(
  raw: unknown,
  source: { source_id: string; source_name: string; page_from: number; page_to: number },
): Record<string, unknown>[] {
  const arr = Array.isArray(raw) ? raw : [];
  return arr
    .filter((e): e is Record<string, unknown> => !!e && typeof e === "object" && !!str((e as any).title))
    .slice(0, 60)
    .map((e) => {
      const date = safeDate(e.date);
      return {
        date,
        // A date the clamp rejected cannot still be called "exact".
        date_confidence: date
          ? (e.date_confidence === "approximate" ? "approximate" : "exact")
          : "unknown",
        type: EVENT_TYPES.has(String(e.type)) ? String(e.type) : "note",
        facility: str(e.facility, 200),
        title: str(e.title, 300),
        detail: str(e.detail, 1200) ?? "",
        values: Array.isArray(e.values)
          ? e.values.slice(0, 30).map((v: any) => ({
              name: str(v?.name, 120) ?? "",
              value: str(v?.value, 120) ?? "",
              unit: str(v?.unit, 40),
              ref: str(v?.ref, 80),
            })).filter((v: any) => v.name && v.value)
          : [],
        medications: Array.isArray(e.medications)
          ? e.medications.slice(0, 30).map((m: any) => ({
              name: str(m?.name, 160) ?? "",
              dose: str(m?.dose, 80),
              frequency: str(m?.frequency, 80),
              duration: str(m?.duration, 80),
            })).filter((m: any) => m.name)
          : [],
        significance: ["high", "medium", "low"].includes(String(e.significance))
          ? String(e.significance)
          : "medium",
        red_flag: e.red_flag === true,
        verbatim: str(e.verbatim, 1200),
        source,
      };
    });
}

// ── Staging purge ─────────────────────────────────────────────────────────────────────
//
// The deletion goes through the Storage API, not SQL: `DELETE FROM storage.objects` drops
// the index row and orphans the S3 blob, which is not a deletion at all for a retention
// guarantee. mark_history_job_purged() is called ONLY after remove() reports success, so a
// failed removal leaves the job a candidate for the next sweep rather than marking it clean.

async function sweepStaging(sb: ReturnType<typeof admin>, limit: number): Promise<number> {
  const { data: candidates } = await sb.rpc("history_purge_candidates", { p_limit: limit });
  const rows = Array.isArray(candidates) ? candidates : [];
  let purged = 0;

  for (const c of rows as Array<{ job_id: string; staged_paths: string[] }>) {
    const paths = (c.staged_paths || []).filter(Boolean);
    if (paths.length === 0) continue;
    const { error } = await sb.storage.from(BUCKET).remove(paths);
    // A path already gone is success, not failure — the object is what had to disappear.
    if (error && !/not.?found/i.test(error.message || "")) continue;
    await sb.rpc("mark_history_job_purged", { p_job_id: c.job_id });
    purged++;
  }
  return purged;
}

// ── Model tier routing ────────────────────────────────────────────────────────────────
//
// 'fast' and 'accurate' can name DIFFERENT PROVIDERS (Gemini vs Claude), so overriding just
// the model name on one resolved config is not enough — each tier needs its own API key.
// Both are resolved through resolveAiConfig with the entitlement DECIDED ONCE and passed in,
// which is what ResolveAiConfigOptions.entitlement exists for: the tier keys are model-routing
// rows, not gateable features, and re-running checkAIAllowed against them would be asking an
// entitlement question about a key no plan has ever heard of.
//
// The meter is then forced back onto the canonical FEATURE_KEY so all extraction spend rolls
// up under one feature in ai_usage_logs regardless of which tier ran.

async function resolveTierConfig(
  hospitalId: string,
  tier: string,
  gate: { allowed: boolean; reason?: string },
): Promise<AiConfig | null> {
  const tierKey = `${FEATURE_KEY}_${tier === "accurate" ? "accurate" : "fast"}`;
  const cfg =
    (await resolveAiConfig(hospitalId, tierKey, MAX_TOKENS, { entitlement: gate })) ??
    (await resolveAiConfig(hospitalId, FEATURE_KEY, MAX_TOKENS, { entitlement: gate })) ??
    resolveAiConfigFromEnv(MAX_TOKENS, hospitalId, FEATURE_KEY);
  if (!cfg) return null;
  if (cfg.meter) cfg.meter = { ...cfg.meter, featureKey: FEATURE_KEY };
  return cfg;
}

// ── One chunk ─────────────────────────────────────────────────────────────────────────

interface ChunkRow {
  id: string;
  source_id: string;
  page_from: number;
  page_to: number;
  attempts: number;
}

interface SourceRow {
  id: string;
  source_name: string;
  source_type: string;
  page_count: number;
  model_tier: string;
  staged_path: string | null;
  document_date: string | null;
}

async function processChunk(
  sb: ReturnType<typeof admin>,
  chunk: ChunkRow,
  source: SourceRow,
  config: AiConfig,
  systemPrompt: string,
  promptVersion: number,
  patientId: string,
  encounterId: string | null,
): Promise<void> {
  if (!source.staged_path) {
    // The scan was purged before this chunk ran — a stalled job that came back after its
    // retention window. Not retryable: the bytes are gone, by design.
    throw Object.assign(new Error("staged object already purged"), { name: "StagingPurged" });
  }

  const { data: blob, error: dlErr } = await sb.storage.from(BUCKET).download(source.staged_path);
  if (dlErr || !blob) {
    throw Object.assign(new Error("download failed"), { name: "StagingUnavailable" });
  }
  const bytes = new Uint8Array(await blob.arrayBuffer());

  const name = source.staged_path.toLowerCase();
  const isPdf = name.endsWith(".pdf");
  const isText = name.endsWith(".txt");

  const pageLabel = chunk.page_from === chunk.page_to
    ? `page ${chunk.page_from}`
    : `pages ${chunk.page_from}-${chunk.page_to}`;

  const instruction =
    `Document: "${source.source_name}" (${pageLabel} of ${source.page_count}).\n` +
    `Transcribe these pages in full, then extract the dated clinical events. ` +
    `Return the JSON object described in your instructions and nothing else.`;

  // Per-call meter attribution. resolveAiConfig cannot know the patient or encounter, and
  // without them the ai_usage_logs row is unattributable PHI-adjacent spend (Ananya).
  const metered: AiConfig = config.meter
    ? { ...config, meter: { ...config.meter, patientId, encounterId: encounterId ?? undefined } }
    : config;

  let content: string;
  if (isText) {
    // DOCX/TXT are extracted to plain text client-side (the browser already has mammoth via
    // documentAI.ts) and staged as .txt, so the worker needs no Office parser at all.
    const text = new TextDecoder().decode(bytes).slice(0, 40_000);
    const { content: c } = await callAiChatWithUsage(
      metered,
      [{ role: "system", content: systemPrompt },
       { role: "user", content: `${instruction}\n\n--- DOCUMENT TEXT ---\n${text}\n--- END ---` }],
      MAX_TOKENS,
      0.1,
    );
    content = c;
  } else {
    if (isPdf && !supportsPdfDocuments(metered)) {
      // Fail loudly rather than sending a PDF to a surface that will answer confidently from
      // the prompt alone without seeing it. On a transcription task that is a fabricated page.
      throw Object.assign(
        new Error("configured model cannot read PDFs"),
        { name: "ProviderCannotReadPdf" },
      );
    }
    const payload = isPdf ? await slicePdf(bytes, chunk.page_from, chunk.page_to) : bytes;
    const { content: c } = await callAiDocument(
      metered,
      [{
        kind: isPdf ? "pdf" : "image",
        mediaType: isPdf ? "application/pdf" : (name.endsWith(".png") ? "image/png" : "image/jpeg"),
        data: bytesToBase64(payload),
      }],
      `${systemPrompt}\n\n${instruction}`,
      MAX_TOKENS,
      0.1,
    );
    content = c;
  }

  const parsed = parseModelJson(content);
  const verbatim = str(parsed.verbatim_text, 60_000);
  const events = clampEvents(parsed.events, {
    source_id: source.id,
    source_name: source.source_name,
    page_from: chunk.page_from,
    page_to: chunk.page_to,
  });

  // A response with neither transcription nor events read nothing. Treat it as a failure so
  // the ledger shows the pages as unreadable, rather than banking an empty success — which
  // would put a green tick over pages nobody has actually seen.
  if (!verbatim && events.length === 0) {
    throw Object.assign(new Error("model returned no content"), { name: "EmptyExtraction" });
  }

  await sb.from("patient_history_source_chunks").update({
    status: "extracted",
    verbatim_text: verbatim,
    extracted: {
      events,
      unreadable: Array.isArray(parsed.unreadable)
        ? parsed.unreadable.slice(0, 20).map((u: unknown) => str(u, 300)).filter(Boolean)
        : [],
    },
    model_used: metered.model,
    model_tier: source.model_tier,
    prompt_version: promptVersion,
    error_name: null,
  }).eq("id", chunk.id);

  // Document-level facts come from whichever chunk saw the header — normally the first, but
  // a cover sheet can push it later, so any chunk may fill a still-empty field. COALESCE
  // semantics: first non-null wins, later chunks never overwrite.
  const patch: Record<string, unknown> = {};
  if (!source.document_date && safeDate(parsed.document_date)) {
    patch.document_date = safeDate(parsed.document_date);
  }
  if (source.source_type === "other" && str(parsed.document_type, 60)) {
    patch.source_type = str(parsed.document_type, 60);
  }
  if (Object.keys(patch).length > 0) {
    await sb.from("patient_history_sources").update(patch).eq("id", source.id);
  }
}

// ── Job run ───────────────────────────────────────────────────────────────────────────

async function runJob(sb: ReturnType<typeof admin>, jobId: string, retryFailed: boolean) {
  const startedAt = Date.now();

  const { data: job } = await sb
    .from("patient_history_ingest_jobs")
    .select("id, hospital_id, patient_id, encounter_id, status, model_tier")
    .eq("id", jobId)
    .maybeSingle();

  if (!job) return json({ error: "Job not found." }, 404);

  // hospital_id comes from the JOB ROW and is used for every subsequent filter. Never from
  // the request body — a caller who guessed a job_id must not also get to choose the tenant
  // it is checked against.
  const hospitalId = job.hospital_id as string;
  const patientId = job.patient_id as string;
  const encounterId = (job.encounter_id as string | null) ?? null;

  if (job.status === "uploading") {
    // Files are still being staged and no tier has been confirmed. Spending here would bill
    // for a bag the doctor has not yet agreed to pay for.
    return json({ status: "uploading", message: "Job is still being staged." });
  }
  if (["complete", "partial", "failed", "cancelled"].includes(job.status as string) && !retryFailed) {
    return json({ status: job.status, message: "Job already finished." });
  }
  if (job.status === "reducing" && !retryFailed) {
    // ai-history-digest owns the job now. Re-entering here would flip it back to 'running',
    // find no open chunks, and fire a SECOND digest — two AI passes and two digest versions
    // for one bag. A stalled reduce is recovered by the purge sweep, not by racing it.
    return json({ status: "reducing", message: "Summary is being built." });
  }

  // First invocation of a new job: take the opportunity to clear anyone else's stalled
  // staging. Bounded to 5 so it cannot turn a doctor's scan into a maintenance window.
  if (job.status === "queued") {
    try { await sweepStaging(sb, 5); } catch { /* never block a scan on housekeeping */ }
  }

  // Entitlement decided ONCE, then handed to both tier resolutions.
  const gate = await checkAIAllowed(sb, hospitalId, FEATURE_KEY);
  if (!gate.allowed) throw new AIDisabledError(gate.reason);

  const { data: reg } = await sb
    .from("prompt_registry")
    .select("system_prompt, version")
    .eq("feature_key", FEATURE_KEY)
    .eq("is_active", true)
    .maybeSingle();
  const systemPrompt = (reg?.system_prompt as string) || FALLBACK_SYSTEM_PROMPT;
  const promptVersion = Number(reg?.version) || PROMPT_VERSION;

  const tierConfigs = new Map<string, AiConfig | null>();
  const configFor = async (tier: string) => {
    if (!tierConfigs.has(tier)) tierConfigs.set(tier, await resolveTierConfig(hospitalId, tier, gate));
    return tierConfigs.get(tier) ?? null;
  };
  if (!(await configFor("fast")) && !(await configFor("accurate"))) {
    await sb.from("patient_history_ingest_jobs")
      .update({ status: "failed", error_name: "NoAiProvider", finished_at: new Date().toISOString() })
      .eq("id", jobId);
    return json({ error: "No AI provider configured. Go to Settings → API Hub." }, 503);
  }

  // started_at is stamped ONCE, on the first transition out of 'queued'.
  //
  // Re-stamping it on every self-re-invocation would silently break the cost audit: the
  // digest sums ai_usage_logs from started_at onwards, so a 300-page job spread over twenty
  // invocations would report only the last 90 seconds of spend — making actual_cost_inr
  // look far cheaper than the estimate the doctor was shown, in the wrong direction.
  await sb.from("patient_history_ingest_jobs")
    .update({
      status: "running",
      ...(job.status === "queued" ? { started_at: new Date().toISOString() } : {}),
    })
    .eq("id", jobId)
    .in("status", ["queued", "running", "complete", "partial", "failed"]);

  // ── Requeue work orphaned by a previous invocation ──────────────────────────────────
  // A chunk left 'running' means the worker died holding it. Its attempt was already
  // counted, so this cannot loop forever — it just gets its remaining tries.
  const staleBefore = new Date(Date.now() - STALE_CHUNK_MINUTES * 60_000).toISOString();
  await sb.from("patient_history_source_chunks")
    .update({ status: "pending" })
    .eq("job_id", jobId).eq("hospital_id", hospitalId)
    .eq("status", "running").lt("updated_at", staleBefore);

  if (retryFailed) {
    await sb.from("patient_history_source_chunks")
      .update({ status: "pending", attempts: 0, error_name: null })
      .eq("job_id", jobId).eq("hospital_id", hospitalId).eq("status", "failed");
  }

  // ── Create chunk rows for any source that has none ──────────────────────────────────
  // This is where the coverage guarantee is established: pageRanges() tiles [1..page_count]
  // with no gaps, and the UNIQUE(source_id, page_from) index makes re-running it after a
  // half-finished write safe rather than duplicating.
  const { data: sources } = await sb
    .from("patient_history_sources")
    .select("id, source_name, source_type, page_count, model_tier, staged_path, document_date, ingest_status")
    .eq("job_id", jobId).eq("hospital_id", hospitalId);

  for (const s of (sources ?? []) as (SourceRow & { ingest_status: string })[]) {
    if (s.ingest_status === "unsupported") continue;
    const { count } = await sb
      .from("patient_history_source_chunks")
      .select("id", { count: "exact", head: true })
      .eq("source_id", s.id).eq("hospital_id", hospitalId);
    if ((count ?? 0) > 0) continue;

    const rows = pageRanges(s.page_count, PAGES_PER_CHUNK).map((r) => ({
      hospital_id: hospitalId,
      patient_id: patientId,
      source_id: s.id,
      job_id: jobId,
      page_from: r.page_from,
      page_to: r.page_to,
      status: "pending",
    }));
    await sb.from("patient_history_source_chunks")
      .upsert(rows, { onConflict: "source_id,page_from", ignoreDuplicates: true });
    await sb.from("patient_history_sources").update({ ingest_status: "chunked" }).eq("id", s.id);
  }

  const sourceById = new Map((sources ?? []).map((s: any) => [s.id, s as SourceRow]));

  // ── Process chunks until the wall budget runs out ───────────────────────────────────
  let processed = 0;
  let contended = 0;

  while (Date.now() - startedAt < WALL_BUDGET_MS) {
    const { data: next } = await sb
      .from("patient_history_source_chunks")
      .select("id, source_id, page_from, page_to, attempts")
      .eq("job_id", jobId).eq("hospital_id", hospitalId)
      .eq("status", "pending")
      .order("page_from", { ascending: true })
      .limit(1);

    const candidate = (next ?? [])[0] as ChunkRow | undefined;
    if (!candidate) break;

    // Claim it. The .eq("status","pending") guard is the whole concurrency story: if a
    // duplicate invocation took it first, this updates zero rows and we move on.
    const { data: claimed } = await sb
      .from("patient_history_source_chunks")
      .update({ status: "running", attempts: candidate.attempts + 1 })
      .eq("id", candidate.id).eq("status", "pending")
      .select("id, source_id, page_from, page_to, attempts")
      .maybeSingle();

    if (!claimed) {
      // Losing every claim in a row means another worker owns this job. Yield rather than
      // spin — without this bound the loop would burn the full 90s doing nothing.
      if (++contended >= 3) break;
      continue;
    }
    contended = 0;

    const source = sourceById.get(claimed.source_id);
    if (!source) {
      await sb.from("patient_history_source_chunks")
        .update({ status: "failed", error_name: "SourceMissing" }).eq("id", claimed.id);
      continue;
    }

    const config = (await configFor(source.model_tier)) ?? (await configFor("fast"));
    if (!config) {
      await sb.from("patient_history_source_chunks")
        .update({ status: "pending", error_name: "NoAiProvider" }).eq("id", claimed.id);
      break;
    }

    try {
      await processChunk(
        sb, claimed as ChunkRow, source, config,
        systemPrompt, promptVersion, patientId, encounterId,
      );
      processed++;
    } catch (err) {
      // Error NAME only — the message can carry a provider echo of the page contents.
      const name = err instanceof Error ? err.name : "UnknownError";
      const exhausted = (claimed.attempts ?? 1) >= MAX_ATTEMPTS;
      const permanent = name === "StagingPurged" || name === "ProviderCannotReadPdf";
      await sb.from("patient_history_source_chunks").update({
        status: exhausted || permanent ? "failed" : "pending",
        error_name: name,
      }).eq("id", claimed.id);
      console.error(`ai-history-ingest chunk ${exhausted || permanent ? "failed" : "retrying"}: ${name}`);
    }
  }

  // ── More to do? Hand off to a fresh invocation. ─────────────────────────────────────
  const { count: remaining } = await sb
    .from("patient_history_source_chunks")
    .select("id", { count: "exact", head: true })
    .eq("job_id", jobId).eq("hospital_id", hospitalId)
    .in("status", ["pending", "running"]);

  if ((remaining ?? 0) > 0) {
    await selfInvoke({ job_id: jobId });
    return json({ status: "running", processed, remaining });
  }

  // ── Terminal. Finalise the ledger, then reduce. ─────────────────────────────────────
  const { data: finalStatus } = await sb.rpc("finalize_history_job", { p_job_id: jobId });

  if (finalStatus === "failed") {
    // Nothing readable at all — there is no digest to build, but the staging still has to
    // go. The hourly sweep would eventually get it; doing it now keeps the window tight.
    try { await sweepStaging(sb, 5); } catch { /* the sweep will retry */ }
    return json({ status: "failed", processed });
  }

  await sb.from("patient_history_ingest_jobs").update({ status: "reducing" }).eq("id", jobId);
  await invokeFunction("ai-history-digest", { job_id: jobId });
  return json({ status: "reducing", processed });
}

// ── Invocation helpers ────────────────────────────────────────────────────────────────
//
// Fire-and-forget: awaiting a self-invoke would chain every batch into one synchronous call
// and time out the outermost request — the exact failure the chunking exists to avoid.
// EdgeRuntime.waitUntil keeps the isolate alive long enough for the request to leave.

async function invokeFunction(fn: string, body: unknown): Promise<void> {
  const url = `${Deno.env.get("SUPABASE_URL")}/functions/v1/${fn}`;
  const req = fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")}`,
    },
    body: JSON.stringify(body),
  }).catch((err) => {
    console.error(`ai-history-ingest could not invoke ${fn}: ${err instanceof Error ? err.name : "UnknownError"}`);
  });

  const rt = (globalThis as { EdgeRuntime?: { waitUntil?: (p: Promise<unknown>) => void } }).EdgeRuntime;
  if (rt?.waitUntil) rt.waitUntil(req);
  else await Promise.race([req, new Promise((r) => setTimeout(r, 250))]);
}

const selfInvoke = (body: unknown) => invokeFunction("ai-history-ingest", body);

// ── Entry ─────────────────────────────────────────────────────────────────────────────

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { job_id, sweep, retry_failed } = await req.json().catch(() => ({}));
    const sb = admin();

    if (sweep) {
      const purged = await sweepStaging(sb, 50);
      return json({ swept: purged });
    }
    if (!job_id) return json({ error: "job_id is required" }, 400);

    return await runJob(sb, String(job_id), retry_failed === true);
  } catch (err) {
    if (err instanceof AIDisabledError) {
      return json({ error: err.message, disabled: true }, 403);
    }
    // NEVER echo the request body, a storage path, or model output — all carry PHI.
    const name = err instanceof Error ? err.name : "UnknownError";
    console.error(`ai-history-ingest failed: ${name}`);
    return json({ error: "History ingestion failed." }, 500);
  }
});
